name: Publish crates
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check that tag version and Cargo.toml version are the same
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "version = $VERSION"
          if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
            echo "version does not match Cargo.toml" >&2
            exit 1
          fi

  ci:
    needs: check-version
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ["check-version", "ci"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Publish
        run: cargo publish
        env:            
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}