name: Security
on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/deny.toml'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          log-level: warn
          manifest-path: ./Cargo.toml
          command: check
          arguments: --all-features